/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MinecraftRouteImport } from './routes/minecraft'
import { Route as ImageRouteImport } from './routes/image'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as CodeitRouteImport } from './routes/codeit'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatChatIdRouteImport } from './routes/chat.$chatId'
import { Route as ApiResearchRouteImport } from './routes/api.research'
import { Route as ApiMinecraftRouteImport } from './routes/api.minecraft'
import { Route as ApiImageRouteImport } from './routes/api.image'
import { Route as ApiCodeitRouteImport } from './routes/api.codeit'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as CreationsUserProjectRouteImport } from './routes/creations.$user.$project'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MinecraftRoute = MinecraftRouteImport.update({
  id: '/minecraft',
  path: '/minecraft',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeitRoute = CodeitRouteImport.update({
  id: '/codeit',
  path: '/codeit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchRoute = ApiResearchRouteImport.update({
  id: '/api/research',
  path: '/api/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMinecraftRoute = ApiMinecraftRouteImport.update({
  id: '/api/minecraft',
  path: '/api/minecraft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodeitRoute = ApiCodeitRouteImport.update({
  id: '/api/codeit',
  path: '/api/codeit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationsUserProjectRoute = CreationsUserProjectRouteImport.update({
  id: '/creations/$user/$project',
  path: '/creations/$user/$project',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/codeit': typeof CodeitRoute
  '/coming-soon': typeof ComingSoonRoute
  '/image': typeof ImageRoute
  '/minecraft': typeof MinecraftRoute
  '/pricing': typeof PricingRoute
  '/research': typeof ResearchRoute
  '/video': typeof VideoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/codeit': typeof ApiCodeitRoute
  '/api/image': typeof ApiImageRoute
  '/api/minecraft': typeof ApiMinecraftRoute
  '/api/research': typeof ApiResearchRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/creations/$user/$project': typeof CreationsUserProjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/codeit': typeof CodeitRoute
  '/coming-soon': typeof ComingSoonRoute
  '/image': typeof ImageRoute
  '/minecraft': typeof MinecraftRoute
  '/pricing': typeof PricingRoute
  '/research': typeof ResearchRoute
  '/video': typeof VideoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/codeit': typeof ApiCodeitRoute
  '/api/image': typeof ApiImageRoute
  '/api/minecraft': typeof ApiMinecraftRoute
  '/api/research': typeof ApiResearchRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/creations/$user/$project': typeof CreationsUserProjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apps': typeof AppsRoute
  '/auth': typeof AuthRoute
  '/codeit': typeof CodeitRoute
  '/coming-soon': typeof ComingSoonRoute
  '/image': typeof ImageRoute
  '/minecraft': typeof MinecraftRoute
  '/pricing': typeof PricingRoute
  '/research': typeof ResearchRoute
  '/video': typeof VideoRoute
  '/api/chat': typeof ApiChatRoute
  '/api/codeit': typeof ApiCodeitRoute
  '/api/image': typeof ApiImageRoute
  '/api/minecraft': typeof ApiMinecraftRoute
  '/api/research': typeof ApiResearchRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/creations/$user/$project': typeof CreationsUserProjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apps'
    | '/auth'
    | '/codeit'
    | '/coming-soon'
    | '/image'
    | '/minecraft'
    | '/pricing'
    | '/research'
    | '/video'
    | '/api/chat'
    | '/api/codeit'
    | '/api/image'
    | '/api/minecraft'
    | '/api/research'
    | '/chat/$chatId'
    | '/creations/$user/$project'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apps'
    | '/auth'
    | '/codeit'
    | '/coming-soon'
    | '/image'
    | '/minecraft'
    | '/pricing'
    | '/research'
    | '/video'
    | '/api/chat'
    | '/api/codeit'
    | '/api/image'
    | '/api/minecraft'
    | '/api/research'
    | '/chat/$chatId'
    | '/creations/$user/$project'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apps'
    | '/auth'
    | '/codeit'
    | '/coming-soon'
    | '/image'
    | '/minecraft'
    | '/pricing'
    | '/research'
    | '/video'
    | '/api/chat'
    | '/api/codeit'
    | '/api/image'
    | '/api/minecraft'
    | '/api/research'
    | '/chat/$chatId'
    | '/creations/$user/$project'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppsRoute: typeof AppsRoute
  AuthRoute: typeof AuthRoute
  CodeitRoute: typeof CodeitRoute
  ComingSoonRoute: typeof ComingSoonRoute
  ImageRoute: typeof ImageRoute
  MinecraftRoute: typeof MinecraftRoute
  PricingRoute: typeof PricingRoute
  ResearchRoute: typeof ResearchRoute
  VideoRoute: typeof VideoRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCodeitRoute: typeof ApiCodeitRoute
  ApiImageRoute: typeof ApiImageRoute
  ApiMinecraftRoute: typeof ApiMinecraftRoute
  ApiResearchRoute: typeof ApiResearchRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
  CreationsUserProjectRoute: typeof CreationsUserProjectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minecraft': {
      id: '/minecraft'
      path: '/minecraft'
      fullPath: '/minecraft'
      preLoaderRoute: typeof MinecraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codeit': {
      id: '/codeit'
      path: '/codeit'
      fullPath: '/codeit'
      preLoaderRoute: typeof CodeitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research': {
      id: '/api/research'
      path: '/api/research'
      fullPath: '/api/research'
      preLoaderRoute: typeof ApiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/minecraft': {
      id: '/api/minecraft'
      path: '/api/minecraft'
      fullPath: '/api/minecraft'
      preLoaderRoute: typeof ApiMinecraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codeit': {
      id: '/api/codeit'
      path: '/api/codeit'
      fullPath: '/api/codeit'
      preLoaderRoute: typeof ApiCodeitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creations/$user/$project': {
      id: '/creations/$user/$project'
      path: '/creations/$user/$project'
      fullPath: '/creations/$user/$project'
      preLoaderRoute: typeof CreationsUserProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppsRoute: AppsRoute,
  AuthRoute: AuthRoute,
  CodeitRoute: CodeitRoute,
  ComingSoonRoute: ComingSoonRoute,
  ImageRoute: ImageRoute,
  MinecraftRoute: MinecraftRoute,
  PricingRoute: PricingRoute,
  ResearchRoute: ResearchRoute,
  VideoRoute: VideoRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCodeitRoute: ApiCodeitRoute,
  ApiImageRoute: ApiImageRoute,
  ApiMinecraftRoute: ApiMinecraftRoute,
  ApiResearchRoute: ApiResearchRoute,
  ChatChatIdRoute: ChatChatIdRoute,
  CreationsUserProjectRoute: CreationsUserProjectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
